{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "7e33ebc4",
   "metadata": {},
   "source": [
    "# Gold Modeling Notebook — Build Star Schema\n",
    "\n",
    "This notebook constructs the Gold layer star schema by transforming refined Silver data into dimensional and fact tables optimized for analytical consumption. It applies deterministic modeling rules, generates surrogate keys, assembles conformed dimensions, and produces a clean fact table suitable for BI tools and semantic models.\n",
    "\n",
    "The modeling process is intentionally stable and predictable: it standardizes dimensional attributes, resolves grain, derives analytical measures, and writes each table as an independent Delta dataset. All environment‑specific values are externalized through configuration, and the notebook mirrors the logic used by the pipeline‑ready script to ensure consistent execution across development and automated orchestration paths."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a989581",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Gold Modeling Notebook\n",
    "# Deterministic Silver → Gold star schema construction\n",
    "# ============================================================\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 1. Initialize Spark\n",
    "# ------------------------------------------------------------\n",
    "from pyspark.sql import SparkSession\n",
    "from pyspark.sql.functions import (\n",
    "    col, trim, lower, monotonically_increasing_id,\n",
    "    year, month, dayofmonth, hour\n",
    ")\n",
    "import json\n",
    "\n",
    "spark = SparkSession.builder.getOrCreate()\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 2. Load configuration\n",
    "# ------------------------------------------------------------\n",
    "config_path = \"/Workspace/Repos/gold/gold-modeling-config.json\"\n",
    "\n",
    "with open(config_path, \"r\") as f:\n",
    "    config = json.load(f)\n",
    "\n",
    "silver_path = config[\"paths\"][\"silver\"]\n",
    "gold_dim_customer_path = config[\"paths\"][\"gold_dim_customer\"]\n",
    "gold_dim_product_path = config[\"paths\"][\"gold_dim_product\"]\n",
    "gold_dim_date_path = config[\"paths\"][\"gold_dim_date\"]\n",
    "gold_fact_sales_path = config[\"paths\"][\"gold_fact_sales\"]\n",
    "write_mode = config[\"write\"][\"mode\"]\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 3. Read Silver data\n",
    "# ------------------------------------------------------------\n",
    "df_silver = (\n",
    "    spark.read\n",
    "         .format(\"delta\")\n",
    "         .load(silver_path)\n",
    ")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 4. Build Dimensions\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "# -------------------------\n",
    "# Customer Dimension\n",
    "# -------------------------\n",
    "df_dim_customer = (\n",
    "    df_silver\n",
    "        .select(\"customer_id\")\n",
    "        .dropDuplicates()\n",
    "        .withColumn(\"customer_key\", monotonically_increasing_id())\n",
    ")\n",
    "\n",
    "# -------------------------\n",
    "# Product Dimension\n",
    "# -------------------------\n",
    "df_dim_product = (\n",
    "    df_silver\n",
    "        .select(\"product_id\")\n",
    "        .dropDuplicates()\n",
    "        .withColumn(\"product_key\", monotonically_increasing_id())\n",
    ")\n",
    "\n",
    "# -------------------------\n",
    "# Date Dimension\n",
    "# -------------------------\n",
    "df_dim_date = (\n",
    "    df_silver\n",
    "        .select(\"order_timestamp\")\n",
    "        .withColumn(\"date_key\", monotonically_increasing_id())\n",
    "        .withColumn(\"year\", year(col(\"order_timestamp\")))\n",
    "        .withColumn(\"month\", month(col(\"order_timestamp\")))\n",
    "        .withColumn(\"day\", dayofmonth(col(\"order_timestamp\")))\n",
    "        .withColumn(\"hour\", hour(col(\"order_timestamp\")))\n",
    ")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 5. Build Fact Table\n",
    "# ------------------------------------------------------------\n",
    "df_fact_sales = (\n",
    "    df_silver\n",
    "        .join(df_dim_customer, \"customer_id\", \"left\")\n",
    "        .join(df_dim_product, \"product_id\", \"left\")\n",
    "        .join(df_dim_date, \"order_timestamp\", \"left\")\n",
    "        .select(\n",
    "            \"customer_key\",\n",
    "            \"product_key\",\n",
    "            \"date_key\",\n",
    "            \"quantity\",\n",
    "            \"unit_price\",\n",
    "            \"total_amount\"\n",
    "        )\n",
    ")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 6. Write Gold Tables\n",
    "# ------------------------------------------------------------\n",
    "(\n",
    "    df_dim_customer.write\n",
    "                   .format(\"delta\")\n",
    "                   .mode(write_mode)\n",
    "                   .save(gold_dim_customer_path)\n",
    ")\n",
    "\n",
    "(\n",
    "    df_dim_product.write\n",
    "                  .format(\"delta\")\n",
    "                  .mode(write_mode)\n",
    "                  .save(gold_dim_product_path)\n",
    ")\n",
    "\n",
    "(\n",
    "    df_dim_date.write\n",
    "                .format(\"delta\")\n",
    "                .mode(write_mode)\n",
    "                .save(gold_dim_date_path)\n",
    ")\n",
    "\n",
    "(\n",
    "    df_fact_sales.write\n",
    "                 .format(\"delta\")\n",
    "                 .mode(write_mode)\n",
    "                 .save(gold_fact_sales_path)\n",
    ")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# 7. Confirmation\n",
    "# ------------------------------------------------------------\n",
    "print(\"Gold star schema modeling completed successfully.\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
